// memecoindle dataset
// Sources: memecoin.wiki (155-coin catalogue + per-article figures), contemporaneous reporting, market data.
// m  = PEAK market cap in $M (approx)
// cm = CURRENT market cap in $M (approx, mid/late-2026 snapshot; refined against memecoin.wiki article data)
// The game grades both by order-of-magnitude range, not exact value.
// c = chain, y = launch year, g = category/type, s = fate (metadata, not a game axis), l = lore, w = memecoin.wiki slug

var CHAINS = ["Solana", "Ethereum", "BNB Chain", "Base", "Robinhood", "Bitcoin", "Cardano", "Stable Chain", "Own chain"];
var EVM_FAMILY = { "Ethereum": 1, "BNB Chain": 1, "Base": 1, "Robinhood": 1, "Stable Chain": 1 };

var CATS = ["Dog", "Cat", "Frog", "Animal", "Character", "Person", "Politics", "Celebrity", "AI", "Joke", "Brand"];
var CAT_FAMILY = {
  "Dog": "animal", "Cat": "animal", "Frog": "animal", "Animal": "animal",
  "Person": "people", "Politics": "people", "Celebrity": "people",
  "AI": "tech", "Brand": "tech",
  "Character": "meme", "Joke": "meme"
};

// Peak market cap ranges (order of magnitude):
// 1: <$10M · 2: $10M–$100M · 3: $100M–$1B · 4: $1B–$10B · 5: $10B+
function capTier(m) { if (m < 10) return 1; if (m < 100) return 2; if (m < 1000) return 3; if (m < 10000) return 4; return 5; }
var TIER_LABELS = ["", "<$10M", "$10M+", "$100M+", "$1B+", "$10B+"];

// Current market cap ranges (finer at the bottom — that's where memecoins live now):
// 1: <$1M · 2: $1M–$10M · 3: $10M–$100M · 4: $100M–$1B · 5: $1B+
function nowTier(m) { if (m < 1) return 1; if (m < 10) return 2; if (m < 100) return 3; if (m < 1000) return 4; return 5; }
var NOW_LABELS = ["", "<$1M", "$1M+", "$10M+", "$100M+", "$1B+"];

var COINS = [
  { n: "Dogecoin", t: "DOGE", c: "Own chain", y: 2013, m: 88000, cm: 10900, g: "Dog", s: "Icon", l: "The 2013 joke that invented the entire category.", w: "dogecoin" },
  { n: "Shiba Inu", t: "SHIB", c: "Ethereum", y: 2020, m: 41000, cm: 2600, g: "Dog", s: "Icon", l: "The self-styled Dogecoin killer that hit $41B in 2021.", w: "shiba_inu" },
  { n: "Pepe", t: "PEPE", c: "Ethereum", y: 2023, m: 11000, cm: 1100, g: "Frog", s: "Icon", l: "The frog that became the largest pure meme coin of its era.", w: "pepe" },
  { n: "Dogwifhat", t: "WIF", c: "Solana", y: 2023, m: 4800, cm: 136, g: "Dog", s: "Icon", l: "A shiba in a knitted hat. It's literally just a dog wif a hat.", w: "dogwifhat" },
  { n: "BONK", t: "BONK", c: "Solana", y: 2022, m: 4000, cm: 250, g: "Dog", s: "Icon", l: "Solana's flagship community dog, airdropped at the chain's lowest hour.", w: "bonk" },
  { n: "Official Trump", t: "TRUMP", c: "Solana", y: 2025, m: 15000, cm: 355, g: "Politics", s: "Scandal", l: "Launched by a sitting president-elect days before inauguration. Briefly among the most valuable memecoins ever.", w: "official_trump" },
  { n: "Melania", t: "MELANIA", c: "Solana", y: 2025, m: 2000, cm: 67, g: "Politics", s: "Scandal", l: "The First Lady's coin. Collapsed sharply; fraud allegations followed in court.", w: "melania" },
  { n: "LIBRA", t: "LIBRA", c: "Solana", y: 2025, m: 4500, cm: 20, g: "Politics", s: "Scandal", l: "Promoted by Argentina's president, dead in hours, triggered criminal probes and a political crisis.", w: "libra" },
  { n: "HAWK", t: "HAWK", c: "Solana", y: 2024, m: 490, cm: 1, g: "Celebrity", s: "Scandal", l: "Hawk Tuah girl's coin: -90% within hours, lawsuit, federal inquiry.", w: "hawk" },
  { n: "YZY", t: "YZY", c: "Solana", y: 2025, m: 3000, cm: 40, g: "Celebrity", s: "Scandal", l: "Kanye's token touched $3B within hours, then collapsed amid insider allegations.", w: "yzy" },
  { n: "SafeMoon", t: "SFM", c: "BNB Chain", y: 2021, m: 8000, cm: 2, g: "Joke", s: "Scandal", l: "The reflection-token mania of 2021. CEO got 100 months in prison.", w: "safemoon" },
  { n: "Squid Game", t: "SQUID", c: "BNB Chain", y: 2021, m: 25, cm: 0.1, g: "Brand", s: "Scandal", l: "The rug that made 'rug pull' mainstream news — you could buy, but never sell.", w: null },
  { n: "SLERF", t: "SLERF", c: "Solana", y: 2024, m: 700, cm: 10, g: "Animal", s: "Scandal", l: "Dev fat-fingered $10M of presale funds into the burn address. It mooned anyway.", w: "slerf" },
  { n: "Gen Z Quant", t: "QUANT", c: "Solana", y: 2024, m: 85, cm: 2, g: "Person", s: "Scandal", l: "A 13-year-old rugged his own coin on livestream. CT revenge-pumped it 100x.", w: "quant" },
  { n: "Pippin", t: "PIPPIN", c: "Solana", y: 2024, m: 900, cm: 18, g: "AI", s: "Scandal", l: "Stick-figure unicorn by the BabyAGI author. Second peak near $900M, then an insider-blamed crash.", w: "pippin" },
  { n: "Zerebro", t: "ZEREBRO", c: "Solana", y: 2024, m: 500, cm: 5, g: "AI", s: "Scandal", l: "Its creator staged his own death as a stunt. Twice, arguably.", w: "zerebro" },
  { n: "DADDY", t: "DADDY", c: "Solana", y: 2024, m: 280, cm: 3, g: "Celebrity", s: "Scandal", l: "Andrew Tate's entry in the celebrity coin war, dogged by insider-buying allegations.", w: "daddy" },
  { n: "Fartcoin", t: "FARTCOIN", c: "Solana", y: 2024, m: 2500, cm: 140, g: "Joke", s: "Faded", l: "Born from an AI's conversation about flatulence. Reached multiple billions. Hot air, literally.", w: "fartcoin" },
  { n: "Goatseus Maximus", t: "GOAT", c: "Solana", y: 2024, m: 1300, cm: 13, g: "AI", s: "Faded", l: "Shilled into existence by the Truth Terminal AI. First pump.fun token to $1B.", w: "goatseus_maximus" },
  { n: "Peanut the Squirrel", t: "PNUT", c: "Solana", y: 2024, m: 2000, cm: 40, g: "Animal", s: "Faded", l: "New York euthanized a pet squirrel and the trenches made it a billion-dollar martyr.", w: "peanut_the_squirrel" },
  { n: "Moo Deng", t: "MOODENG", c: "Solana", y: 2024, m: 614, cm: 36, g: "Animal", s: "Faded", l: "A viral baby pygmy hippo from a Thai zoo, tokenized within days.", w: "moo_deng" },
  { n: "Popcat", t: "POPCAT", c: "Solana", y: 2023, m: 2000, cm: 50, g: "Cat", s: "Faded", l: "The 2020 pop-pop meme became the first cat coin to $1B.", w: "popcat" },
  { n: "Cat in a Dogs World", t: "MEW", c: "Solana", y: 2024, m: 1000, cm: 40, g: "Cat", s: "Faded", l: "Launched as the resistance to dog coin dominance. Briefly a billion-dollar cat.", w: "cat_in_a_dogs_world" },
  { n: "Brett", t: "BRETT", c: "Base", y: 2024, m: 2300, cm: 36, g: "Character", s: "Faded", l: "Matt Furie's Boy's Club character, adopted as Base's flagship meme.", w: "brett" },
  { n: "Mog Coin", t: "MOG", c: "Ethereum", y: 2023, m: 1500, cm: 36, g: "Cat", s: "Faded", l: "The internet's first 'culture coin'. Joycat with sunglasses, $1.5B peak.", w: "mog_coin" },
  { n: "Turbo", t: "TURBO", c: "Ethereum", y: 2023, m: 1000, cm: 50, g: "Frog", s: "Alive", l: "Designed by GPT-4 on a $69 budget. The original AI-made memecoin.", w: "turbo" },
  { n: "Floki", t: "FLOKI", c: "BNB Chain", y: 2021, m: 3300, cm: 190, g: "Dog", s: "Faded", l: "Named after Elon's puppy, rebranded into a sprawling 'utility ecosystem'.", w: "floki" },
  { n: "Baby Doge Coin", t: "BABYDOGE", c: "BNB Chain", y: 2021, m: 1000, cm: 150, g: "Dog", s: "Faded", l: "Deflationary son-of-Doge famous for burning quadrillions of tokens.", w: "baby_doge_coin" },
  { n: "Dogelon Mars", t: "ELON", c: "Ethereum", y: 2021, m: 1100, cm: 50, g: "Dog", s: "Faded", l: "Doge, but on Mars, in 2021's most honest ticker grab.", w: null },
  { n: "Book of Meme", t: "BOME", c: "Solana", y: 2024, m: 1500, cm: 30, g: "Joke", s: "Faded", l: "Darkfarms' attempt to archive meme culture on-chain forever. Presale to $1.5B in days.", w: "book_of_meme" },
  { n: "Dog Go To The Moon", t: "DOG", c: "Bitcoin", y: 2024, m: 1000, cm: 63, g: "Dog", s: "Alive", l: "The flagship of Bitcoin Runes, etched at the 2024 halving, airdropped free.", w: "dog_go_to_the_moon" },
  { n: "PENGU", t: "PENGU", c: "Solana", y: 2024, m: 2800, cm: 450, g: "Animal", s: "Alive", l: "Pudgy Penguins' token — the NFT brand that made it out, complete with ETF filing.", w: "pengu" },
  { n: "Snek", t: "SNEK", c: "Cardano", y: 2023, m: 500, cm: 30, g: "Animal", s: "Alive", l: "Cardano's fair-launched house snake, its most valuable native token.", w: "snek" },
  { n: "SPX6900", t: "SPX", c: "Ethereum", y: 2023, m: 2100, cm: 260, g: "Joke", s: "Alive", l: "A parody of the S&P 500 that became the belief coin of the 2025 cycle.", w: "spx6900" },
  { n: "Gigachad", t: "GIGA", c: "Solana", y: 2024, m: 648, cm: 25, g: "Person", s: "Faded", l: "Ernest Khalimov's jawline, community-takeover edition.", w: "gigachad" },
  { n: "Apu Apustaja", t: "APU", c: "Ethereum", y: 2023, m: 500, cm: 5, g: "Frog", s: "Faded", l: "The gentle helper frog. A coin 'for all frens'.", w: "apu_apustaja" },
  { n: "Wojak", t: "WOJAK", c: "Ethereum", y: 2023, m: 140, cm: 5, g: "Character", s: "Faded", l: "The bald feels guy, tokenized in the post-PEPE shitcoin spring.", w: "wojak" },
  { n: "Milady Meme Coin", t: "LADYS", c: "Ethereum", y: 2023, m: 380, cm: 30, g: "Character", s: "Faded", l: "Milady Maker aesthetics plus one Elon tweet equals +5,000%.", w: "milady_meme_coin" },
  { n: "HarryPotterObamaSonic10Inu", t: "BITCOIN", c: "Ethereum", y: 2023, m: 370, cm: 40, g: "Joke", s: "Faded", l: "Absurdism as a service. Trades under the ticker BITCOIN.", w: "harrypotterobamasonic10inu" },
  { n: "Samoyedcoin", t: "SAMO", c: "Solana", y: 2021, m: 600, cm: 15, g: "Dog", s: "Faded", l: "Widely recognized as Solana's first memecoin, from the 2021 bull.", w: "samoyedcoin" },
  { n: "COPE", t: "COPE", c: "Solana", y: 2021, m: 150, cm: 1, g: "Joke", s: "Faded", l: "Ranked traders by the accuracy of their public calls. Early Serum-era relic.", w: "cope" },
  { n: "analoS", t: "ANALOS", c: "Solana", y: 2023, m: 120, cm: 2, g: "Joke", s: "Faded", l: "Solana spelled backwards. That's it. Nine figures anyway.", w: "analos" },
  { n: "Silly Dragon", t: "SILLY", c: "Solana", y: 2023, m: 150, cm: 3, g: "Character", s: "Faded", l: "Anatoly's Halloween dragon costume, briefly Solana's unofficial mascot.", w: "silly_dragon" },
  { n: "MYRO", t: "MYRO", c: "Solana", y: 2023, m: 350, cm: 10, g: "Dog", s: "Faded", l: "Named after Solana co-founder Raj Gokal's actual dog.", w: "myro" },
  { n: "PONKE", t: "PONKE", c: "Solana", y: 2023, m: 400, cm: 30, g: "Animal", s: "Alive", l: "An angry gambling monkey, one of the longest-lived mascots of its cohort.", w: "ponke" },
  { n: "WEN", t: "WEN", c: "Solana", y: 2024, m: 370, cm: 2, g: "Joke", s: "Faded", l: "Created from a fractionalized poem, airdropped to a million wallets by Jupiter.", w: "wen" },
  { n: "Jeo Boden", t: "BODEN", c: "Solana", y: 2024, m: 650, cm: 1, g: "Politics", s: "Collapsed", l: "The misspelled Biden parody that led 2024's PolitiFi wave — until Biden dropped out.", w: "jeo_boden" },
  { n: "Doland Tremp", t: "TREMP", c: "Solana", y: 2024, m: 60, cm: 1, g: "Politics", s: "Faded", l: "The bullish half of the Boden/Tremp PolitiFi pair.", w: "doland_tremp" },
  { n: "Tooker Kurlson", t: "TOOKER", c: "Solana", y: 2024, m: 40, cm: 0.5, g: "Politics", s: "Faded", l: "Tucker Carlson via deliberate misspelling and cartoon mock interviews.", w: "tooker_kurlson" },
  { n: "PWEASE", t: "PWEASE", c: "Solana", y: 2025, m: 45, cm: 2, g: "Politics", s: "Faded", l: "Babyface JD Vance, minted from the Oval Office confrontation memes.", w: "pwease" },
  { n: "CAR Coin", t: "CAR", c: "Solana", y: 2025, m: 900, cm: 2, g: "Politics", s: "Collapsed", l: "A national memecoin endorsed by the Central African Republic's president. -95% in two days.", w: "central_african_republic_coin" },
  { n: "Burnie Senders", t: "BURNIE", c: "Solana", y: 2026, m: 25, cm: 3, g: "Politics", s: "Faded", l: "Bernie Sanders as Soviet sleeper agent, pump.fun to $25M in three weeks.", w: "burnie_senders" },
  { n: "MOTHER", t: "MOTHER", c: "Solana", y: 2024, m: 227, cm: 0.7, g: "Celebrity", s: "Faded", l: "Iggy Azalea's coin — the celebrity launch that actually kept showing up.", w: "mother" },
  { n: "Jailstool", t: "JAILSTOOL", c: "Solana", y: 2025, m: 267, cm: 5, g: "Celebrity", s: "Collapsed", l: "Dave Portnoy's nine-figure pump, crashed within days.", w: "jailstool" },
  { n: "GREED", t: "GREED", c: "Solana", y: 2025, m: 41, cm: 0.5, g: "Celebrity", s: "Collapsed", l: "Portnoy's 'experiment in greed'. He sold his 35% and it fell 99%. Experiment concluded.", w: "greed" },
  { n: "Vine Coin", t: "VINE", c: "Solana", y: 2025, m: 500, cm: 30, g: "Brand", s: "Collapsed", l: "Vine's cofounder rode the do-it-for-the-Vine revival rumors to $500M.", w: "vine_coin" },
  { n: "Jelly My Jelly", t: "JELLYJELLY", c: "Solana", y: 2025, m: 250, cm: 15, g: "Brand", s: "Faded", l: "A Venmo cofounder's video-app token that later set off the Hyperliquid short-squeeze crisis.", w: "jelly_my_jelly" },
  { n: "GME on Solana", t: "GME", c: "Solana", y: 2024, m: 200, cm: 10, g: "Brand", s: "Faded", l: "Unaffiliated GameStop tribute that 50x'd when Roaring Kitty came back online.", w: "gme_on_solana" },
  { n: "Unicorn Fart Dust", t: "UFD", c: "Solana", y: 2024, m: 285, cm: 13, g: "Joke", s: "Faded", l: "A gold bug made it to mock crypto and accidentally became beloved.", w: "unicorn_fart_dust" },
  { n: "Useless Coin", t: "USELESS", c: "Solana", y: 2025, m: 361, cm: 72, g: "Joke", s: "Alive", l: "Its only stated feature is being useless. The emblem of the anti-utility trade.", w: "useless_coin" },
  { n: "Housecoin", t: "HOUSE", c: "Solana", y: 2025, m: 120, cm: 15, g: "Joke", s: "Faded", l: "Finally, a house you can afford: on the blockchain.", w: "housecoin" },
  { n: "Chillhouse", t: "CHILLHOUSE", c: "Solana", y: 2025, m: 30, cm: 5, g: "Joke", s: "Faded", l: "Parodied Housecoin, flipped its own target, ran the 'thoughts on chillhouse?' DM campaign.", w: "chillhouse" },
  { n: "Chill Guy", t: "CHILLGUY", c: "Solana", y: 2024, m: 550, cm: 20, g: "Character", s: "Faded", l: "Just a chill cartoon dog, a TikTok mania, and one very unchill copyright dispute.", w: "chill_guy" },
  { n: "LOCKIN", t: "LOCKIN", c: "Solana", y: 2024, m: 50, cm: 8, g: "Joke", s: "Alive", l: "Hold with total conviction. The trench slang, tokenized.", w: "lockin" },
  { n: "Retardio", t: "RETARDIO", c: "Solana", y: 2024, m: 230, cm: 10, g: "Joke", s: "Faded", l: "The coin whose name became trench culture's most-used word.", w: "retardio" },
  { n: "Sigma", t: "SIGMA", c: "Solana", y: 2024, m: 155, cm: 5, g: "Joke", s: "Faded", l: "The sigma male grindset, on-chain.", w: "sigma" },
  { n: "Aura", t: "AURA", c: "Solana", y: 2024, m: 230, cm: 10, g: "Joke", s: "Alive", l: "Tokenized Gen Z aura points. Ran a year after launch, unnoticed until it wasn't.", w: "aura" },
  { n: "NEET", t: "NEET", c: "Solana", y: 2025, m: 49, cm: 24, g: "Joke", s: "Alive", l: "The anti-work cult coin that funds real protests with creator revenue.", w: "neet" },
  { n: "unc", t: "UNC", c: "Solana", y: 2026, m: 15, cm: 8, g: "Joke", s: "Alive", l: "Gen Z slang for an older guy; a whale bought a third and airdropped it away.", w: "unc" },
  { n: "Buttcoin", t: "BUTTCOIN", c: "Solana", y: 2025, m: 60, cm: 25, g: "Joke", s: "Alive", l: "Crypto's oldest insult, finally tradeable.", w: "buttcoin" },
  { n: "LMAO", t: "LMAO", c: "Solana", y: 2025, m: 12, cm: 8, g: "Joke", s: "Alive", l: "The only pitch is laughter. A pump.fun survivor.", w: "lmao" },
  { n: "TESTICLE", t: "TESTICLE", c: "Solana", y: 2026, m: 10, cm: 5, g: "Joke", s: "Alive", l: "The entire premise is the ticker. Briefly top volume on Solana.", w: "testicle" },
  { n: "Titcoin", t: "TITCOIN", c: "Solana", y: 2024, m: 120, cm: 10, g: "Joke", s: "Faded", l: "Flagship of the late-2024 vulgar ticker meta.", w: "titcoin" },
  { n: "Uranus", t: "URANUS", c: "Solana", y: 2025, m: 70, cm: 15, g: "Joke", s: "Faded", l: "The oldest planet pun on the internet, whale-accumulated to $70M.", w: "uranus" },
  { n: "MarsCoin", t: "MARSCOIN", c: "BNB Chain", y: 2026, m: 3, cm: 3, g: "Joke", s: "Alive", l: "Reviving Elon's 2021 promise to CZ: 'There will definitely be a MarsCoin!'", w: "marscoin" },
  { n: "Mubarak", t: "MUBARAK", c: "BNB Chain", y: 2025, m: 200, cm: 18, g: "Character", s: "Faded", l: "Anchor of the Arabic meme wave on BSC after CZ bought in.", w: "mubarak" },
  { n: "TST", t: "TST", c: "BNB Chain", y: 2025, m: 490, cm: 15, g: "Joke", s: "Faded", l: "A throwaway example token from a BNB tutorial video. Traders made it a $490M joke.", w: "tst" },
  { n: "Broccoli", t: "BROCCOLI", c: "BNB Chain", y: 2025, m: 400, cm: 20, g: "Dog", s: "Faded", l: "CZ revealed his dog's name and BSC launched a hundred broccolis by dinnertime.", w: "broccoli" },
  { n: "Koma Inu", t: "KOMA", c: "BNB Chain", y: 2024, m: 140, cm: 10, g: "Dog", s: "Faded", l: "The self-styled Son of Shiba, with DWF Labs backing.", w: "koma_inu" },
  { n: "Cheems", t: "CHEEMS", c: "BNB Chain", y: 2025, m: 170, cm: 97, g: "Dog", s: "Alive", l: "Balltze's memorial coin family — the Binance-listed flagship of Cheems lore.", w: "cheems" },
  { n: "Degen", t: "DEGEN", c: "Base", y: 2024, m: 160, cm: 33, g: "Joke", s: "Alive", l: "Farcaster's tipping token that grew its own layer-3 blockchain.", w: "degen_coin" },
  { n: "Clanker", t: "CLANKER", c: "Base", y: 2024, m: 143, cm: 12, g: "AI", s: "Alive", l: "The autonomous deployer bot that launches tokens on request. Acquired by Farcaster.", w: "clanker" },
  { n: "aixbt", t: "AIXBT", c: "Base", y: 2024, m: 800, cm: 40, g: "AI", s: "Faded", l: "The AI commentator that became CT's most-followed analyst.", w: "aixbt" },
  { n: "Luna (Virtuals)", t: "LUNA", c: "Base", y: 2024, m: 250, cm: 10, g: "AI", s: "Faded", l: "Virtuals' first agent: a virtual idol livestreaming to a TikTok following.", w: "luna_virtuals" },
  { n: "ai16z", t: "AI16Z", c: "Solana", y: 2024, m: 2500, cm: 10, g: "AI", s: "Collapsed", l: "The AI-managed VC DAO that led the agent meta, rebranded to ElizaOS, and was declared dead by its own founder.", w: "ai16z" },
  { n: "ELIZA", t: "ELIZA", c: "Solana", y: 2024, m: 100, cm: 2, g: "AI", s: "Collapsed", l: "Casualty of the naming dispute where an endorsed relaunch nuked the community token in minutes.", w: "eliza" },
  { n: "Degen Spartan AI", t: "DEGENAI", c: "Solana", y: 2024, m: 105, cm: 5, g: "AI", s: "Faded", l: "An AI resurrection of the pseudonymous trader DegenSpartan.", w: "degen_spartan_ai" },
  { n: "Dolos the Bully", t: "BULLY", c: "Solana", y: 2024, m: 250, cm: 5, g: "AI", s: "Faded", l: "An autonomous insult comic named for the Greek god of trickery.", w: "dolos_the_bully" },
  { n: "GRIFFAIN", t: "GRIFFAIN", c: "Solana", y: 2024, m: 600, cm: 10, g: "AI", s: "Collapsed", l: "Natural-language on-chain agent engine, $600M at the top of the meta.", w: "griffain" },
  { n: "Swarms", t: "SWARMS", c: "Solana", y: 2025, m: 600, cm: 10, g: "AI", s: "Collapsed", l: "Multi-agent orchestration framework from the AI meta's framework rotation.", w: "swarms" },
  { n: "AI Rig Complex", t: "ARC", c: "Solana", y: 2024, m: 600, cm: 15, g: "AI", s: "Collapsed", l: "The Rust-framework wing of the AI agent meta.", w: "ai_rig_complex" },
  { n: "Dasha", t: "VVAIFU", c: "Solana", y: 2024, m: 200, cm: 3, g: "AI", s: "Faded", l: "Token of the first no-code AI waifu launchpad.", w: "dasha_vvaifu" },
  { n: "ACT", t: "ACT", c: "Solana", y: 2024, m: 900, cm: 15, g: "AI", s: "Collapsed", l: "Act I: The AI Prophecy — +2,000% on a Binance listing, then a notorious flash crash.", w: "act" },
  { n: "gork", t: "GORK", c: "Solana", y: 2025, m: 40, cm: 5, g: "AI", s: "Faded", l: "A Grok parody account that mooned when Musk renamed himself Gorklon Rust.", w: "gork" },
  { n: "Ani Grok Companion", t: "ANI", c: "Solana", y: 2025, m: 87, cm: 0.5, g: "AI", s: "Faded", l: "The canonical token of the Grok anime-companion wave.", w: "ani_grok_companion" },
  { n: "Valentine", t: "VALENTINE", c: "Solana", y: 2025, m: 18, cm: 1, g: "AI", s: "Faded", l: "Ani's brother coin: +88,000% on Musk's naming announcement.", w: "valentine" },
  { n: "Ghiblification", t: "GHIBLI", c: "Solana", y: 2025, m: 50, cm: 2, g: "Character", s: "Faded", l: "Flagship of the ChatGPT Ghibli-image wave of March 2025.", w: "ghiblification" },
  { n: "Kekius Maximus", t: "KEKIUS", c: "Solana", y: 2024, m: 77, cm: 10, g: "Frog", s: "Faded", l: "Pepe as a Roman gladiator; +1,700% when Musk took the name as his X persona.", w: "kekius_maximus" },
  { n: "LUCE", t: "LUCE", c: "Solana", y: 2024, m: 85, cm: 5, g: "Character", s: "Faded", l: "The Vatican unveiled an anime mascot and the trenches did what they do.", w: "luce" },
  { n: "Fwog", t: "FWOG", c: "Solana", y: 2024, m: 700, cm: 20, g: "Frog", s: "Faded", l: "The community rallied behind the collapsed project's unpaid artist.", w: "fwog" },
  { n: "michi", t: "MICHI", c: "Solana", y: 2024, m: 322, cm: 0.6, g: "Cat", s: "Faded", l: "One of pump.fun's first breakout successes.", w: "michi" },
  { n: "Nubcat", t: "NUB", c: "Solana", y: 2024, m: 100, cm: 5, g: "Cat", s: "Faded", l: "Tied in community lore to Ansem's cat. Bitget-listed within days.", w: "nubcat" },
  { n: "MANEKI", t: "MANEKI", c: "Solana", y: 2024, m: 120, cm: 8, g: "Cat", s: "Faded", l: "The lucky cat figurine; nine figures within a day.", w: "maneki" },
  { n: "Shark Cat", t: "SC", c: "Solana", y: 2024, m: 390, cm: 10, g: "Cat", s: "Faded", l: "Celebrity cat Nala in a shark costume, licensing dispute included.", w: "shark_cat" },
  { n: "Pajamas Cat", t: "PAJAMAS", c: "Solana", y: 2024, m: 8, cm: 1, g: "Cat", s: "Faded", l: "Honors the first cat video ever uploaded to YouTube. pump.fun folklore.", w: "pajamas_cat" },
  { n: "Hosico", t: "HOSICO", c: "Solana", y: 2025, m: 75, cm: 0.7, g: "Cat", s: "Faded", l: "The internet-famous Scottish Straight, flagship of the letsbonk era.", w: "hosico" },
  { n: "Catecoin", t: "CATE", c: "Solana", y: 2026, m: 70, cm: 11, g: "Cat", s: "Alive", l: "Cat cult coin carried by a community takeover led by PoorGoat.", w: "catecoin" },
  { n: "KET", t: "KET", c: "Solana", y: 2026, m: 15, cm: 10, g: "Cat", s: "Alive", l: "Community takeover under the slogan 'don't be a pussy'.", w: "ket" },
  { n: "wiwiwi", t: "WIWIWI", c: "Solana", y: 2026, m: 10, cm: 8, g: "Cat", s: "Alive", l: "Flagship of the cult coin rotation: 'cults over cabals'.", w: "wiwiwi" },
  { n: "BILLY", t: "BILLY", c: "Solana", y: 2024, m: 150, cm: 5, g: "Dog", s: "Faded", l: "Abandoned by its dev minutes after launch, rebuilt by the community.", w: "billy" },
  { n: "DUKO", t: "DUKO", c: "Solana", y: 2024, m: 70, cm: 1, g: "Dog", s: "Faded", l: "Hand-drawn and marketed as Solana's cutest dog.", w: "duko" },
  { n: "Jotchua", t: "JOTCHUA", c: "Solana", y: 2026, m: 25, cm: 10, g: "Dog", s: "Alive", l: "The Perro Dinero golden retriever; a single-day 100x.", w: "jotchua" },
  { n: "Harambe on Solana", t: "HARAMBE", c: "Solana", y: 2024, m: 88, cm: 3, g: "Animal", s: "Faded", l: "A memorial coin for the gorilla, abandoned then community-revived.", w: "harambe_on_solana" },
  { n: "Sad Hamster", t: "HAMMY", c: "Solana", y: 2024, m: 71, cm: 2, g: "Animal", s: "Faded", l: "The pouting TikTok hamster; devs sold, community pushed on.", w: "sad_hamster" },
  { n: "Slothana", t: "SLOTH", c: "Solana", y: 2024, m: 100, cm: 2, g: "Animal", s: "Faded", l: "Raised $15M in a send-SOL presale at the end of the presale meta.", w: "slothana" },
  { n: "Mumu the Bull", t: "MUMU", c: "Solana", y: 2024, m: 60, cm: 3, g: "Animal", s: "Faded", l: "The cartoon bull from crypto's mumu-and-bobo tradition.", w: "mumu_the_bull" },
  { n: "GUMMY", t: "GUMMY", c: "Solana", y: 2024, m: 150, cm: 0.5, g: "Character", s: "Collapsed", l: "The 4/20 gummy bear pump: $150M for a weekend, then -99%.", w: "gummy" },
  { n: "moonpig", t: "MOONPIG", c: "Solana", y: 2025, m: 50, cm: 8, g: "Animal", s: "Faded", l: "A pig in a spacesuit, late launchpad-era standout.", w: "moonpig" },
  { n: "White Whale", t: "WHITEWHALE", c: "Solana", y: 2026, m: 40, cm: 5, g: "Animal", s: "Collapsed", l: "Crashed when Remus — of the legendary $370 entry — sold.", w: "white_whale" },
  { n: "Jimothy", t: "JIMOTHY", c: "Solana", y: 2026, m: 5, cm: 4, g: "Animal", s: "Alive", l: "A Seattle raccoon, +331% in a day off one Elon video.", w: "jimothy" },
  { n: "Shadow The Eagle", t: "SHADOW", c: "Solana", y: 2026, m: 5, cm: 4, g: "Animal", s: "Alive", l: "The Big Bear eagle who found a new companion; the trenches celebrated.", w: "shadow_the_eagle" },
  { n: "CHONKETHA", t: "CHONKETHA", c: "Solana", y: 2026, m: 12, cm: 10, g: "Animal", s: "Alive", l: "Chonketha the Wet Beaver rode the summer animal meta to a KCEX listing.", w: "chonketha" },
  { n: "PUNCH", t: "PUNCH", c: "Solana", y: 2026, m: 10, cm: 7, g: "Animal", s: "Alive", l: "The zoo macaque with the IKEA plushie — a coin that actually sent donations back.", w: "punch" },
  { n: "Smoking Chicken Fish", t: "SCF", c: "Solana", y: 2024, m: 80, cm: 25, g: "Joke", s: "Alive", l: "A cigarette-smoking trout in a chicken. Registered as an actual church.", w: "smoking_chicken_fish" },
  { n: "Tung Tung Tung Sahur", t: "TRIPLET", c: "Solana", y: 2025, m: 30, cm: 15, g: "Character", s: "Alive", l: "Indonesian Ramadan brainrot, now an established character coin.", w: "tung_tung_tung_sahur" },
  { n: "Udin", t: "UDIN", c: "Solana", y: 2026, m: 1, cm: 0.7, g: "Character", s: "Alive", l: "Social footprint enormous, market cap never broke $1M.", w: "udin" },
  { n: "Chiikawa", t: "CHIIKAWA", c: "Solana", y: 2026, m: 15, cm: 12, g: "Character", s: "Alive", l: "Unlicensed tribute that surged with the franchise's record-breaking film.", w: "chiikawa" },
  { n: "Neegy", t: "NEEGY", c: "Solana", y: 2026, m: 10, cm: 7, g: "Character", s: "Alive", l: "A Fortnite voice-chat catchphrase, briefly top volume on pump.fun.", w: "neegy" },
  { n: "MANLET", t: "MANLET", c: "Solana", y: 2026, m: 5, cm: 4, g: "Character", s: "Alive", l: "The underdog companion coin of the Black Bull wave.", w: "manlet" },
  { n: "Cupsey", t: "CUPSEY", c: "Solana", y: 2026, m: 15, cm: 12, g: "Character", s: "Alive", l: "The plush cup mascot of pump.fun, with a real merch line.", w: "cupsey_coin" },
  { n: "CyberLeek", t: "CYBERLEEK", c: "Solana", y: 2026, m: 8, cm: 6, g: "Character", s: "Alive", l: "Token of the GTA 6 leaker; its pool launched three days before the leak.", w: "cyberleek" },
  { n: "Doom", t: "DOOM", c: "Solana", y: 2026, m: 10, cm: 7, g: "Brand", s: "Alive", l: "Sandy Petersen posted the mint address himself; the game pays SOL to top fraggers.", w: "doom" },
  { n: "TROLL", t: "TROLL", c: "Solana", y: 2024, m: 283, cm: 42, g: "Character", s: "Alive", l: "Trollface lay dormant for months, then bought the actual meme rights.", w: "troll" },
  { n: "The Black Bull", t: "ANSEM", c: "Solana", y: 2026, m: 362, cm: 96, g: "Person", s: "Alive", l: "An anon handed Ansem the supply; he airdropped the fees back.", w: "the_black_bull" },
  { n: "IKUN", t: "IKUN", c: "Solana", y: 2025, m: 30, cm: 10, g: "Celebrity", s: "Faded", l: "Cai Xukun fandom memes, breakout of the Chinese meme wave.", w: "ikun" },
  { n: "Gas Town", t: "GAS", c: "Solana", y: 2026, m: 60, cm: 5, g: "Brand", s: "Collapsed", l: "Tokenized Steve Yegge's AI orchestrator without asking him. He stepped back; it stepped down.", w: "gas_town" },
  { n: "Dupe", t: "DUPE", c: "Solana", y: 2025, m: 40, cm: 8, g: "Brand", s: "Faded", l: "Flagship of the Believe launchpad's 'internet capital markets' wave.", w: "dupe" },
  { n: "Unipeg", t: "UPEG", c: "Ethereum", y: 2026, m: 5, cm: 4, g: "Brand", s: "Alive", l: "Uniswap-v4-hook unicorns rendered fully on-chain; neither NFT nor normal token.", w: "unipeg" },
  { n: "FEFER", t: "FEFER", c: "Stable Chain", y: 2026, m: 9, cm: 6, g: "Character", s: "Alive", l: "The first memecoin on Tether's gas chain; its frenzy set network records.", w: "fefer" },
  { n: "Frong", t: "FRONG", c: "Robinhood", y: 2026, m: 12, cm: 10, g: "Frog", s: "Alive", l: "Minted through Uniswap's unreleased launchpad contracts six days early.", w: "frong" },
  { n: "Cash Cat", t: "CASHCAT", c: "Robinhood", y: 2026, m: 224, cm: 90, g: "Cat", s: "Alive", l: "The cat Robinhood almost named the company after — first memecoin in the Robinhood app.", w: "cash_cat" },
  { n: "Hoodrat", t: "HOODRAT", c: "Robinhood", y: 2026, m: 10, cm: 7, g: "Animal", s: "Alive", l: "A Night Riders-linked rat from the chain's July takeover.", w: "hoodrat" },
  { n: "Pons", t: "PONS", c: "Robinhood", y: 2026, m: 65, cm: 21, g: "Brand", s: "Alive", l: "The dominant launchpad token of Robinhood Chain; $100K to $65M in two weeks.", w: "pons" },
  { n: "TENDIES", t: "TENDIES", c: "Robinhood", y: 2026, m: 33, cm: 20, g: "Joke", s: "Alive", l: "WallStreetBets flavor for the chain's first meme summer.", w: "tendies" },
  { n: "StonkBroker", t: "STONKBROKER", c: "Robinhood", y: 2026, m: 30, cm: 25, g: "Brand", s: "Alive", l: "Pixel-art broker NFTs with real wallets holding tokenized stocks.", w: "stonkbroker" },
  { n: "TYGR", t: "TYGR", c: "Robinhood", y: 2026, m: 10, cm: 8, g: "Cat", s: "Alive", l: "The kitten in Roaring Kitty's avatar — a 2008 Czech village cat, finally identified.", w: "tygr" },
  { n: "Wishbone", t: "WISHBONE", c: "Robinhood", y: 2026, m: 8, cm: 5, g: "Dog", s: "Alive", l: "A dog dressed as Robin Hood, early launch of the July wave.", w: "wishbone" },
  { n: "POOH", t: "POOH", c: "Robinhood", y: 2026, m: 2, cm: 1.5, g: "Character", s: "Alive", l: "Riding Winnie's 2026 centenary with a small circle of dedicated posters.", w: "pooh" },
  { n: "Brodie", t: "BRODIE", c: "Robinhood", y: 2026, m: 8, cm: 6, g: "Dog", s: "Alive", l: "Robinhood's real office dog from 2016, tokenized a decade later.", w: "brodie" },
  { n: "TOAD", t: "TOAD", c: "Solana", y: 2026, m: 20, cm: 5.5, g: "Frog", s: "Alive", l: "El Sapo Pepe, the Argentine kids' TV toad from 1988 — 'the first Pepe'.", w: "toad" },
  { n: "Neiro", t: "NEIRO", c: "Ethereum", y: 2024, m: 1180, cm: 80, g: "Dog", s: "Faded", l: "Kabosu's successor dog sparked a coin war and a controversial double Binance listing.", w: "neiro" }
];
