// Fetch coin logos for the memecoindle dataset.
// Tries CoinGecko search first (best quality, 250px), falls back to DexScreener.
// Writes img/<TICKER>.png and logos.js manifest. Throttled to respect free rate limits.
// Usage: node tools/fetch-logos.js [--only MISSING]
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
eval(fs.readFileSync(path.join(ROOT, "data.js"), "utf8"));
const IMG_DIR = path.join(ROOT, "img");
if (!fs.existsSync(IMG_DIR)) fs.mkdirSync(IMG_DIR);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

async function jget(url) {
  const res = await fetch(url, { headers: { "User-Agent": "memecoindle-logo-fetch/1.0" } });
  if (!res.ok) throw new Error("HTTP " + res.status);
  return res.json();
}

async function download(url, dest) {
  const res = await fetch(url, { headers: { "User-Agent": "memecoindle-logo-fetch/1.0" } });
  if (!res.ok) throw new Error("HTTP " + res.status);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 400) throw new Error("too small (" + buf.length + "b)");
  fs.writeFileSync(dest, buf);
  return buf.length;
}

async function fromCoinGecko(coin) {
  for (const q of [coin.n, coin.t]) {
    try {
      const j = await jget("https://api.coingecko.com/api/v3/search?query=" + encodeURIComponent(q));
      await sleep(2200);
      const hits = (j.coins || []).filter((h) => h.large && !/missing_/.test(h.large));
      // prefer exact symbol match, then exact name match
      let hit = hits.find((h) => norm(h.symbol) === norm(coin.t)) ||
                hits.find((h) => norm(h.name) === norm(coin.n));
      if (hit) return hit.large;
    } catch (e) {
      if (/429/.test(e.message)) { await sleep(30000); } else { await sleep(2200); }
    }
  }
  return null;
}

async function fromDexScreener(coin) {
  for (const q of [coin.t, coin.n]) {
    try {
      const j = await jget("https://api.dexscreener.com/latest/dex/search?q=" + encodeURIComponent(q));
      await sleep(600);
      const pairs = (j.pairs || []).filter((p) => p.info && p.info.imageUrl &&
        norm(p.baseToken.symbol) === norm(coin.t));
      // highest liquidity match wins
      pairs.sort((a, b) => ((b.liquidity && b.liquidity.usd) || 0) - ((a.liquidity && a.liquidity.usd) || 0));
      if (pairs[0]) return pairs[0].info.imageUrl;
    } catch (e) { await sleep(600); }
  }
  return null;
}

(async () => {
  const onlyMissing = process.argv.includes("--only") || process.argv.includes("--missing");
  const manifest = {};
  let got = 0, missed = [];
  for (const coin of COINS) {
    const dest = path.join(IMG_DIR, coin.t + ".png");
    const rel = "img/" + coin.t + ".png";
    if (fs.existsSync(dest) && fs.statSync(dest).size > 400) {
      manifest[coin.t] = rel; got++;
      if (onlyMissing) continue;
      else continue; // never refetch existing
    }
    let url = await fromCoinGecko(coin);
    let src = "coingecko";
    if (!url) { url = await fromDexScreener(coin); src = "dexscreener"; }
    if (url) {
      try {
        const size = await download(url, dest);
        manifest[coin.t] = rel; got++;
        console.log("OK  " + coin.t.padEnd(12) + src.padEnd(12) + (size / 1024).toFixed(1) + "KB");
      } catch (e) {
        missed.push(coin.t);
        console.log("ERR " + coin.t.padEnd(12) + "download failed: " + e.message);
      }
    } else {
      missed.push(coin.t);
      console.log("--  " + coin.t.padEnd(12) + "no source found");
    }
  }
  const js = "// generated by tools/fetch-logos.js — ticker -> logo path. Missing tickers fall back to a procedural badge.\nvar LOGOS = " +
    JSON.stringify(manifest, null, 0) + ";\n";
  fs.writeFileSync(path.join(ROOT, "logos.js"), js);
  console.log("\nDONE: " + got + "/" + COINS.length + " logos; missing: " + (missed.join(", ") || "none"));
})();
